// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineExamSystem.Data;

#nullable disable

namespace OnlineExamSystem.Migrations
{
    [DbContext(typeof(OnlineExamSystemContext))]
    [Migration("20260622100318_initOnlineExamSystem")]
    partial class initOnlineExamSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineExamSystem.Models.AIProctoringLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<string>("ConfirmedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<bool>("FromBrowserSecurity")
                        .HasColumnType("bit");

                    b.Property<bool>("FromComputerVision")
                        .HasColumnType("bit");

                    b.Property<bool>("FromSEB")
                        .HasColumnType("bit");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConfirmedCheating")
                        .HasColumnType("bit");

                    b.Property<string>("SnapshotPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeDetected")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarningLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AIProctoringLogs");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.AssignedExam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("StudentUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("AssignedExams");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowReview")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoSubmitWhenCheating")
                        .HasColumnType("bit");

                    b.Property<bool>("BanRetakeAfterCheating")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DetectAltTab")
                        .HasColumnType("bit");

                    b.Property<bool>("DetectBooksOrNotes")
                        .HasColumnType("bit");

                    b.Property<bool>("DetectCopyPaste")
                        .HasColumnType("bit");

                    b.Property<bool>("DetectDevTools")
                        .HasColumnType("bit");

                    b.Property<bool>("DetectExternalDevices")
                        .HasColumnType("bit");

                    b.Property<bool>("DetectIdle")
                        .HasColumnType("bit");

                    b.Property<bool>("DetectMultiMonitor")
                        .HasColumnType("bit");

                    b.Property<bool>("DetectMultipleFaces")
                        .HasColumnType("bit");

                    b.Property<bool>("DetectOtherPerson")
                        .HasColumnType("bit");

                    b.Property<bool>("DetectPhone")
                        .HasColumnType("bit");

                    b.Property<bool>("DetectRightClick")
                        .HasColumnType("bit");

                    b.Property<bool>("DetectTabSwitch")
                        .HasColumnType("bit");

                    b.Property<bool>("DetectWindowBlur")
                        .HasColumnType("bit");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("EnableAIEssayGrading")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableAIProctoring")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableBehaviorAnalytics")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableEyeTracking")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableFaceTracking")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableFullscreen")
                        .HasColumnType("bit");

                    b.Property<bool>("EnablePlagiarismDetection")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableViolationPenalty")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableWebcamMonitoring")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EssayFeedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EssayScore")
                        .HasColumnType("float");

                    b.Property<int>("ExamSessionId")
                        .HasColumnType("int");

                    b.Property<bool>("ForceZeroScoreWhenCheating")
                        .HasColumnType("bit");

                    b.Property<bool>("FullscreenAlerts")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<bool>("LockExamAfterCheating")
                        .HasColumnType("bit");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<int>("MaxWarnings")
                        .HasColumnType("int");

                    b.Property<double>("PenaltyPerViolation")
                        .HasColumnType("float");

                    b.Property<bool>("RandomAnswerOrder")
                        .HasColumnType("bit");

                    b.Property<int>("RandomQuestionCount")
                        .HasColumnType("int");

                    b.Property<bool>("RandomQuestionOrder")
                        .HasColumnType("bit");

                    b.Property<bool>("SaveWebcamSnapshots")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowAnswerAfterSubmit")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowCameraBeforeStart")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("TotalScore")
                        .HasColumnType("float");

                    b.Property<int>("WarningPenaltyStart")
                        .HasColumnType("int");

                    b.Property<int>("WebcamSnapshotInterval")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamSessionId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.ExamQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionBankId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("QuestionBankId");

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.ExamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AiSuspiciousScore")
                        .HasColumnType("float");

                    b.Property<int>("AltTabCount")
                        .HasColumnType("int");

                    b.Property<bool>("AltTabDetected")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoSubmitted")
                        .HasColumnType("bit");

                    b.Property<bool>("BannedFromRetake")
                        .HasColumnType("bit");

                    b.Property<int>("BlurCount")
                        .HasColumnType("int");

                    b.Property<bool>("BookDetected")
                        .HasColumnType("bit");

                    b.Property<int>("CopyPasteCount")
                        .HasColumnType("int");

                    b.Property<bool>("CopyPasteDetected")
                        .HasColumnType("bit");

                    b.Property<int>("DevToolsCount")
                        .HasColumnType("int");

                    b.Property<bool>("DevToolsDetected")
                        .HasColumnType("bit");

                    b.Property<decimal>("EssayScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("ExamSessionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("EyeTrackingScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FaceTrackingScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ForceZeroScore")
                        .HasColumnType("bit");

                    b.Property<bool>("FullscreenViolation")
                        .HasColumnType("bit");

                    b.Property<int>("FullscreenViolationCount")
                        .HasColumnType("int");

                    b.Property<bool>("IdleDetected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEssayGraded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("LockReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MultiMonitorDetected")
                        .HasColumnType("bit");

                    b.Property<bool>("MultipleFaceDetected")
                        .HasColumnType("bit");

                    b.Property<bool>("OtherPersonDetected")
                        .HasColumnType("bit");

                    b.Property<decimal>("PenaltyScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PhoneDetected")
                        .HasColumnType("bit");

                    b.Property<bool>("RightClickDetected")
                        .HasColumnType("bit");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SuspiciousAiDetected")
                        .HasColumnType("bit");

                    b.Property<string>("TeacherComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ViolationAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViolationCount")
                        .HasColumnType("int");

                    b.Property<string>("ViolationDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViolationImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WebcamDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("WebcamSnapshotPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WindowBlurDetected")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("ExamSessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("ExamResults");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.ExamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ExamSessions");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.ExamViolation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExamViolations");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.QuestionBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectAnswerJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Difficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QuestionBanks");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CopyPasteDetected")
                        .HasColumnType("bit");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("ExamSessionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SuspiciousAiDetected")
                        .HasColumnType("bit");

                    b.Property<int>("TabSwitchCount")
                        .HasColumnType("int");

                    b.Property<int>("UnansweredQuestions")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViolationCount")
                        .HasColumnType("int");

                    b.Property<int>("WrongAnswers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("ExamSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.StudentAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExamResultId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamResultId");

                    b.HasIndex("QuestionId");

                    b.ToTable("StudentAnswers");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.StudentExamAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("bit");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmitTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("StudentExamAttempt");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoginCount")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.Violation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Violations");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectAnswerJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("MatchingJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.AssignedExam", b =>
                {
                    b.HasOne("OnlineExamSystem.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.Exam", b =>
                {
                    b.HasOne("OnlineExamSystem.Models.ExamSession", "ExamSession")
                        .WithMany("Exams")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSession");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.ExamQuestion", b =>
                {
                    b.HasOne("OnlineExamSystem.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineExamSystem.Models.QuestionBank", "QuestionBank")
                        .WithMany()
                        .HasForeignKey("QuestionBankId");

                    b.Navigation("Exam");

                    b.Navigation("QuestionBank");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.ExamResult", b =>
                {
                    b.HasOne("OnlineExamSystem.Models.Exam", "Exam")
                        .WithMany("ExamResults")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineExamSystem.Models.ExamSession", "ExamSession")
                        .WithMany("ExamResults")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnlineExamSystem.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("ExamSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.Result", b =>
                {
                    b.HasOne("OnlineExamSystem.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnlineExamSystem.Models.ExamSession", "ExamSession")
                        .WithMany()
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineExamSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("ExamSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.StudentAnswer", b =>
                {
                    b.HasOne("OnlineExamSystem.Models.ExamResult", null)
                        .WithMany("StudentAnswers")
                        .HasForeignKey("ExamResultId");

                    b.HasOne("Question", null)
                        .WithMany("StudentAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineExamSystem.Models.StudentExamAttempt", b =>
                {
                    b.HasOne("OnlineExamSystem.Models.Exam", "Exam")
                        .WithMany("StudentExamAttempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.HasOne("OnlineExamSystem.Models.Exam", null)
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineExamSystem.Models.Exam", b =>
                {
                    b.Navigation("ExamResults");

                    b.Navigation("Questions");

                    b.Navigation("StudentExamAttempts");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.ExamResult", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("OnlineExamSystem.Models.ExamSession", b =>
                {
                    b.Navigation("ExamResults");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.Navigation("StudentAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
